version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    container_name: ride-hailing-db
    environment:
      POSTGRES_DB: ride_hailing
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ride_hailing"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ride-hailing-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ride_hailing
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: